spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto:
        validate
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/Komputer Domowy/IdeaProjects/SpringUdemy/todo-db'

management:
  endpoints:
    web:
      exposure:
        include: '*'